language: node_js
node_js:
- "6.9.4"
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
env:
  - CXX=g++-4.8
addons:
  apt:
    packages:
    - gcc-4.8
    - g++-4.8
